# Generated by Django 5.1.5 on 2025-01-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_first_name_customer_name_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_name',
        ),
    ]
