# Generated by Django 5.1.5 on 2025-01-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_product_order_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='username',
            field=models.CharField(default='guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=9),
        ),
    ]
