# Generated by Django 5.1.5 on 2025-01-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cart_username_alter_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='unnamed order', max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
